version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

  # playwright:
  #   image: mcr.microsoft.com/playwright/python:v1.45.0-jammy
  #   container_name: playwright
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./tests:/tests
  #   command: tail -f /dev/null # Keeps container running

volumes:
  jenkins_home:
