name: Playwright Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Github Workspace 
        run: |
          make list-workspace

      - name: Run Docker Setup
        run: |
          make docker-build

      - name: Run Test
        run: |
          make docker-run-test

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/