name: Playwright Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Github Workspace 
        run: |
          echo "Current Directory:"
          pwd

          echo ""
          echo "Files in current directory:"
          ls -la

          echo ""
          echo "Recursive directory tree:"
          ls -R

      - name: Run Docker Setup
        run: |
          make ci

      - name: List Docker Workspace
        run: |
          make ci

      - name: Run Test
        run: |
          make test

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/